### ISSUE TITLE
Browse of HDroidGUI and NetIO

### ISSUE THREAD

**Issue by gvaronas** [alkresin/HDroidGUI#4]
Hi Alex:

[Google]

First I want to express my appreciation for their efforts in developing this wonderful tool.
I've done some tests with HDroidGUI and describe my results here:
With the utilitarian "newproject.exe" I created a new project called "hdNetIO".
I modified the code examples for an APK that allows me to make a table BROWSE "test.dbf" located in the "C:\hb32\tests" folder.
When I compile the project with "build.bat" for the APK I have to run the "build.bat" 2 or 3 times.
The first time I get this:
# 

C:\android\projects\hdNetIO>build.bat
No se pudo encontrar C:\android\projects\hdNetIO\src\org\harbour\hdNetIO\R.java
Acceso denegado.
Acceso denegado.
Acceso denegado.
Harbour 3.2.0dev (r1503052135)
Copyright (c) 1999-2015, http://harbour-project.org/

C:\android\projects\hdNetIO>c:/Android/android-ndk-r10d\prebuilt\windows\bin\make.exe -f c:/Android/android-ndk-r10d/build/core/build-local.mk 1>a1.out 2>a2.out

C:\android\projects\hdNetIO>call c:/Android/sdk/build-tools/22.0.1/aapt.exe package -f -m -S res -J src -M AndroidManifest.xml -I c:/Android/sdk/platforms/android-22/android.jar

C:\android\projects\hdNetIO>call C:/PROGRA~2/java/jdk1.7.0_75/bin/javac -d obj -cp c:/Android/sdk/platforms/android-22/android.jar;C:\android\projects\HDroidGUI\libs -sourcepath src src/org\harbour\hdNetIO/*.java
javac: directory not found: obj
Usage: javac <options> <source files>
use -help for a list of possible options
Presione una tecla para continuar . . .
# C:\android\projects\hdNetIO>

the second time, sometimes I get this:
# 

C:\android\projects\hdNetIO>build.bat
No se pudo encontrar C:\android\projects\hdNetIO\src\org\harbour\hdNetIO\R.java
El sistema no puede encontrar el archivo especificado.
Acceso denegado.
Acceso denegado.
El sistema no puede encontrar el archivo especificado.
Harbour 3.2.0dev (r1503052135)
Copyright (c) 1999-2015, http://harbour-project.org/

C:\android\projects\hdNetIO>c:/Android/android-ndk-r10d\prebuilt\windows\bin\make.exe -f c:/Android/android-ndk-r10d/build/core/build-local.mk 1>a1.out 2>a2.out

C:\android\projects\hdNetIO>call c:/Android/sdk/build-tools/22.0.1/aapt.exe package -f -m -S res -J src -M AndroidManifest.xml -I c:/Android/sdk/platforms/android-22/android.jar

C:\android\projects\hdNetIO>call C:/PROGRA~2/java/jdk1.7.0_75/bin/javac -d obj -cp c:/Android/sdk/platforms/android-22/android.jar;C:\android\projects\HDroidGUI\libs -sourcepath src src/org\harbour\hdNetIO/*.java

C:\android\projects\hdNetIO>call c:/Android/sdk/build-tools/22.0.1/dx.bat --dex --output=bin/classes.dex obj C:\android\projects\HDroidGUI\libs

UNEXPECTED TOP-LEVEL ERROR:
java.io.FileNotFoundException: bin\classes.dex (El sistema no puede encontrar la ruta especificada)
at java.io.FileOutputStream.open(Native Method)
at java.io.FileOutputStream.<init>(FileOutputStream.java:221)
at java.io.FileOutputStream.<init>(FileOutputStream.java:110)
at com.android.dx.command.dexer.Main.openOutput(Main.java:940)
at com.android.dx.command.dexer.Main.runMonoDex(Main.java:316)
at com.android.dx.command.dexer.Main.run(Main.java:246)
at com.android.dx.command.dexer.Main.main(Main.java:215)
at com.android.dx.command.Main.main(Main.java:106)
# Presione una tecla para continuar . . .

and in the second or third time, and believe me the APK and I get this:
# 

C:\android\projects\hdNetIO>build.bat
No se pudo encontrar C:\android\projects\hdNetIO\src\org\harbour\hdNetIO\R.java
El sistema no puede encontrar el archivo especificado.
El sistema no puede encontrar el archivo especificado.
Harbour 3.2.0dev (r1503052135)
Copyright (c) 1999-2015, http://harbour-project.org/

C:\android\projects\hdNetIO>c:/Android/android-ndk-r10d\prebuilt\windows\bin\make.exe -f c:/Android/android-ndk-r10d/build/core/build-local.mk 1>a1.out 2>a2.out

C:\android\projects\hdNetIO>call c:/Android/sdk/build-tools/22.0.1/aapt.exe package -f -m -S res -J src -M AndroidManifest.xml -I c:/Android/sdk/platforms/android-22/android.jar

C:\android\projects\hdNetIO>call C:/PROGRA~2/java/jdk1.7.0_75/bin/javac -d obj -cp c:/Android/sdk/platforms/android-22/android.jar;C:\android\projects\HDroidGUI\libs -sourcepath src src/org\harbour\hdNetIO/*.java

C:\android\projects\hdNetIO>call c:/Android/sdk/build-tools/22.0.1/dx.bat --dex--output=bin/classes.dex obj C:\android\projects\HDroidGUI\libs
'lib/armeabi/libharbour.so'...
'lib/armeabi/libh4droid.so'...
error de herramienta de claves: java.lang.Exception: No se ha generado el par de claves, el alias <key2> ya existe
java.lang.Exception: No se ha generado el par de claves, el alias <key2> ya existe
at sun.security.tools.KeyTool.doGenKeyPair(KeyTool.java:1529)
at sun.security.tools.KeyTool.doCommands(KeyTool.java:969)
at sun.security.tools.KeyTool.run(KeyTool.java:340)
at sun.security.tools.KeyTool.main(KeyTool.java:333)
jar signed.

Warning:
No -tsa or -tsacert is provided and this jar is not timestamped. Without a times
tamp, users may not be able to validate this jar after the signer certificate's
expiration date (2042-08-27) or after any future revocation date.
Verifying alignment of bin/hdNetIO.apk (4)...
50 META-INF/MANIFEST.MF (OK - compressed)
362 META-INF/KEY2.SF (OK - compressed)
740 META-INF/KEY2.RSA (OK - compressed)
1857 AndroidManifest.xml (OK - compressed)
2590 classes.dex (OK - compressed)
22783 lib/armeabi/libharbour.so (OK - compressed)
1067338 lib/armeabi/libh4droid.so (OK - compressed)
Verification succesful
Presione una tecla para continuar . . .
# C:\android\projects\hdNetIO>

What could be happening?

Ok, after obtaining the APK, charge NETIO on a PC with Windows 7 Ultimate 64 bits as follows:
# 

Microsoft Windows [Versión 6.1.7601]
Copyright (c) 2009 Microsoft Corporation. Reservados todos los derechos.

C:\Users\SySGVS>c:\hb32\bin\hbnetio -iface=192.168.1.34 -rootdir=c:\hb32
Harbour NETIO Server 3.2.0dev (r1503052135)
Copyright (c) 2009-2015, Przemyslaw Czerpak, Viktor Szakats
http://harbour-project.org/

2015-04-11 16:56:42.969 Ready to accept connections.
2015-04-11 16:56:42.969 Listening on: 192.168.1.34:2941
2015-04-11 16:56:42.969 Root filesystem: c:\hb32
2015-04-11 16:56:42.969 RPC support: disabled
2015-04-11 16:56:42.969 Encryption: disabled
#2015-04-11 16:56:42.969 RPC filter module: not set

Then I install and run the APK on my cell phone and displayed like this:

![image](https://cloud.githubusercontent.com/assets/4166636/7209842/fac49564-e511-11e4-83b9-1f307f4c6c61.png)

But when I try to navigate beyond the record about 50, the APK aborted and get this:

![image](https://cloud.githubusercontent.com/assets/4166636/7209868/3651a518-e512-11e4-90ef-06daa5677d25.png)

What could be happening?

Deputy project folder "HDNetIO"

BestRegards
GVS

**Comment by mauriservice** [comment]
Hi Alex,
With browse I have the same problem , I dont use netio

Maurizio

**Comment by alkresin** [comment]
Fixed.
Should work correctly now.

**Comment by gvaronas** [comment]
Thanks Alex .
Now navigation works well , but became slow and unstable and sometimes hangs , does not work the option to modify .

BestRegards
GVS

**Comment by jezda1** [comment]
Hi Alex,
I have same problem. When I try to navigate dbf database beyond the record 48, the APK aborted???
